mode: debug

http:
  ip: 0.0.0.0
  port: 8080

#mysql:
#  ip: localhost
#  port: 3306
#  user: root
#  password:

#redis:
#  addr: localhost:6379
#  password:

log:
  level: debug
  path: app.log
  format: json
  maxSize: 1
  # consoleEnable Whether to enable outputting logs to the console as the sametime
  consoleEnable: true

#auth:
#  acl:
#    appId: ""
#    secretKey: ""
#    url: ""
#    resourceName:
#      - key: xxx
#        value: yyy
secretKey: ""
