mode: debug

http:
  ip: 0.0.0.0
  port: 8000

mysql:
  ip: mysql
  port: 3306
  user: root
  password: 

redis:
  addr: redis:6379
  password: 

log:
  level: debug
  path: app.log
  format: json
  maxSize: 1
  consoleEnable: false

auth:
  acl:
    appId: ""
    secretKey: ""
    url: ""
    resourceName:
      - key: xxx
        value: yyy
secretKey: ""
